apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-control-proxy-rolebinding
  labels:
    app.kubernetes.io/name: admission-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-control-proxy-role
subjects:
- kind: ServiceAccount
  name: admission-control
  namespace: admission-control
