apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-control-proxy-role
  labels:
    app.kubernetes.io/name: admission-control
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
