apiVersion: v1
kind: Service
metadata:
  name: admission-control-service
  namespace: admission-control
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
    app.kubernetes.io/name: admission-control
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
    app.kubernetes.io/name: admission-control
  ports:
  - port: 443